apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flask-app
  namespace: default   # Spécifie l'espace de noms par défaut
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: agomesdacosta3/kuber
        ports:
        - containerPort: 5001
